### ISSUE TITLE
unavailable

### ISSUE THREAD

**Issue by oneoy** [AyymericM/mailninja#1]
I don't know why I met such a problem

![1](https://user-images.githubusercontent.com/38435398/39831898-66bdca58-53f8-11e8-9958-ea37462d9fa4.png)

**Comment by aymxdd** [comment]
Hey,
That's because you only ran the server which works like a REST API.
The client is a different code which is located in the `/src` folder and run separately from the server.
I'm updating the documentation right now.

**Comment by oneoy** [comment]
![ubuntu 64 -2018-05-12-17-59-01](https://user-images.githubusercontent.com/38435398/39956222-a969fae4-560e-11e8-9472-fb48f74b89a0.png)
Sometimes this is a mistake》Error: Networking error. Please check your connection or try again later.
, I don't understand why it's wrong.

**Comment by aymxdd** [comment]
Can you show me the error you got on the console ? And console.log the
response of the server ?

**Comment by oneoy** [comment]
Compiled successfully!

You can now view mail_ninja in the browser.

  Local:            http://localhost:3000/
  On Your Network:  http://192.168.1.103:3000/

Note that the development build is not optimized.
To create a production build, use yarn build.

**Comment by oneoy** [comment]
The above is a mistake on the console. I don't know how to solve it.
